In [2]:
import pandas as pd
import numpy as np
data={"x1": [4,8,13,7], "x2": [11,4,5,14]}
df=pd.DataFrame(data)

In [3]:
df

x1  x2
0   4  11
1   8   4
2  13   5
3   7  14

In [54]:
def mean(x):
    return x.mean()
def std(x):
    return x.std()
def scaled(X):
    X_mean=mean(X)
    X_std=std(X)
    return (X-X_mean)/X_std
def cov(Z):
    return Z.cov()
def eigen(Z_cov):
    return np.linalg.eig(Z_cov)
X1=df["x1"]
X2=df["x2"]
X1_mean, X1_std=mean(X1),std(X1)
X2_mean, X2_std=mean(X2),std(X1)
Z1=scaled(X1)
Z2=scaled(X2)
d={"x1":Z1, "x2":Z2}
std_data=pd.DataFrame(d)
std_data

x1        x2
0 -1.069045  0.521286
1  0.000000 -0.938315
2  1.336306 -0.729800
3 -0.267261  1.146829

In [55]:
Z_cov=cov(std_data)
Z_cov

x1        x2
x1  1.000000 -0.613006
x2 -0.613006  1.000000

In [56]:
eigenvalue, eigenvector= eigen(Z_cov)


In [57]:
eigenvalue

array([1.61300603, 0.38699397])

In [58]:
eigenvector

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [59]:
idx=eigenvalue.argsort()[::-1]
eigenvalue=eigenvalue[idx]
eigenvector=eigenvector[:,idx]
eigenvalue

array([1.61300603, 0.38699397])

In [60]:
projection_mat=eigenvector[:,1] #if n_components are 1

In [61]:
projection_mat

array([0.70710678, 0.70710678])

In [62]:
pd.DataFrame.dot(std_data, projection_mat)

0   -0.387324
1   -0.663489
2    0.428864
3    0.621949
dtype: float64

In [68]:
var=np.cumsum(eigenvalue)/np.sum(eigenvalue)

In [70]:
n_components=np.argmax(var>=0.85)+1
n_components

2

In [71]:
u=eigenvector[:,:n_components]
u

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [84]:
pca_component=pd.DataFrame(u, columns=["PCA1", "PCA2"], index=['X1', 'X2'])

In [85]:
pca_component

PCA1      PCA2
X1  0.707107  0.707107
X2 -0.707107  0.707107